### ISSUE TITLE
command line error

### ISSUE THREAD

**Issue by mostafa3** [neoighodaro/laravel-pusher-web-notifications#3]
when i typed php artisan serve the command line reply with 

`PHP Warning:  require(C:\xampp\htdocs\laravel-pusher-web-notifications-master\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\laravel-pusher-web-notifications-master\bootstrap\autoload.php on line 17`

**Comment by neoighodaro** [comment]
Run composer install

On Jul 26, 2018 at 6:19 AM, mostafa3 <notifications@github.com> wrote:


when i typed php artisan serve the command line reply with

PHP Warning:
require(C:\xampp\htdocs\laravel-pusher-web-notifications-master\bootstrap/../vendor/autoload.php):
failed to open stream: No such file or directory in
C:\xampp\htdocs\laravel-pusher-web-notifications-master\bootstrap\autoload.php
on line 17

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/neoighodaro/laravel-pusher-web-notifications/issues/3>,
or mute the thread
